<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PG01CBAC" ignored="0" name="Test" tests="8" failures="2" timestamp="12 Feb 2019 17:00:47 GMT" time="0.06" errors="0">
  <testcase name="test1" time="0.011" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at MyTests.TC_21_RetryLogicAtRunTime.test1(TC_21_RetryLogicAtRunTime.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="MyTests.TC_21_RetryLogicAtRunTime">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at MyTests.TC_21_RetryLogicAtRunTime.test2(TC_21_RetryLogicAtRunTime.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
